name = "domain-alert"
pages_build_output_dir = "./dist"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2024-09-23"

[vars]
  WHOIS_PROXY_URL = "https://n4lulr10x3.execute-api.sa-east-1.amazonaws.com"
  DATABASE_URL = "file:./prisma/dev.db"
  ASTRO_BASE_PATH = "/whois"
  PUBLIC_VAPID_KEY= "BD_gFcm9ay4QhE7vNZyokBKqKdMIYlXyR0p1e9SH7eX84b4beNC0R4uD7AiQnQBtjLFQGd8kN2X3-awABqW69j8"
  PRIVATE_VAPID_KEY= "KCwm9kF2OK1jlYDtpasypOld--c3IXntU_ftzibng0s"

[[d1_databases]]
binding = "domain_monitor"
database_name = "domain-monitor"
database_id = "8b21eb9b-08fb-47e5-889c-cd2a68181e0b"
migrations_dir = "migrations"
